const GOOGLE_MAPS_API_KEY = "AIzaSyAFrF_D0WsbMpx6_Bx1qxhDavzAYYUdzPE";
const MAPBOX_TOKEN = "pk.eyJ1IjoibWFwYWRtaW4xYzJkIiwiYSI6ImNrbGtoMmgxbTBneGIyeHA1aDN4YzdvOXcifQ.RXYaSerbN3o6W03_U0N1fw";
const MAP_ID = "795c40cc70364250";

export { GOOGLE_MAPS_API_KEY, MAPBOX_TOKEN, MAP_ID };